### ISSUE TITLE
Can't create new taxon

### ISSUE THREAD

**Issue by LengTech11** [channainfo/commissioner#1893]
```
Application spree_starter


⚠️ Error occurred in production ⚠️
A *RuntimeError* occurred in *taxons#create*.


Exception:
Locking a record with unpersisted changes is not supported. Use `save` to persist the changes, or `reload` to discard them explicitly.


Set by controller:
{:user=>"40"}


Request:
```
* url : https://api-production.bookme.plus/admin/taxonomies/3/taxons
* http_method : POST
* ip_address : 43.230.192.190
* parameters : {"authenticity_token"=>"[FILTERED]", "taxon"=>{"name"=>"The Awaken The Potential", "hide_from_nav"=>"0", "parent_id"=>"9"}, "controller"=>"spree/admin/taxons", "action"=>"create", "taxonomy_id"=>"3"}
* timestamp : 2024-09-04 12:29:01 +0700
```


Backtrace:
```
* /app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/locking/pessimistic.rb:70:in `lock!'
* /app/vendor/bundle/ruby/3.2.0/gems/awesome_nested_set-3.5.0/lib/awesome_nested_set/model.rb:202:in `right_most_bound'
* /app/vendor/bundle/ruby/3.2.0/gems/awesome_nested_set-3.5.0/lib/awesome_nested_set/model.rb:258:in `set_default_left_and_right'
* /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:400:in `block in make_lambda'
* /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
```
```
<img width="1512" alt="Screenshot 2024-09-06 at 9 56 14 in the morning" src="https://github.com/user-attachments/assets/b3e4635e-f31b-4485-8f87-6dedd3ae94ae">

Ref: https://github.com/zammad/zammad/issues/3664

**Comment by LengTech11** [comment]
#### To resolve the Create Taxon with_lock issue, you need to update all instances of Taxonomy and Taxon. This issue is now closed.
