### ISSUE TITLE
fix Noticed::ResponseUnsuccessful when push to ios device

### ISSUE THREAD

**Issue by panhachom** [channainfo/commissioner#844]
Application spree_starter

⚠️ Error occurred in staging ⚠️
A *Noticed::ResponseUnsuccessful* occurred in *customer_notifications#send_test*.

Exception:
Noticed::ResponseUnsuccessful

Set by controller:
{:user=>"1"}

Request:
```
* url : https://staging-server.contigo.asia/admin/customer_notifications/3/send_test
* http_method : POST
* ip_address : 43.230.192.190
* parameters : {"authenticity_token"=>"[FILTERED]", "notification_id"=>"3", "user_ids"=>["", "42"], "commit"=>"Send", "controller"=>"spree/admin/customer_notifications", "action"=>"send_test", "customer_notification_id"=>"3"}
* timestamp : 2023-11-21 17:01:07 +0700
```

Backtrace:
```
* /app/vendor/bundle/ruby/3.2.0/gems/noticed-1.6.3/lib/noticed/delivery_methods/base.rb:88:in `post'
* /app/vendor/bundle/ruby/3.2.0/gems/noticed-1.6.3/lib/noticed/delivery_methods/fcm.rb:21:in `block in deliver'
* /app/vendor/bundle/ruby/3.2.0/gems/noticed-1.6.3/lib/noticed/delivery_methods/fcm.rb:20:in `each'
* /app/vendor/bundle/ruby/3.2.0/gems/noticed-1.6.3/lib/noticed/delivery_methods/fcm.rb:20:in `deliver'
* /app/vendor/bundle/ruby/3.2.0/gems/noticed-1.6.3/lib/noticed/delivery_methods/base.rb:55:in `block in perform'
```

**Comment by panhachom** [comment]
solve in  #853
