### ISSUE TITLE
PG::UndefinedTable: ERROR:  relation "spree_products" does not exist

### ISSUE THREAD

**Issue by theachoem** [channainfo/commissioner#90]
```s
Caused by:
PG::UndefinedTable: ERROR:  relation "spree_products" does not exist
LINE 8:  WHERE a.attrelid = '"spree_products"'::regclass
                            ^
/Users/theachoem/Coding/Webs/central_market/commissioner/spec/dummy/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
Running extension installation generator...
         run  bundle exec rake railties:install:migrations FROM=spree_cm_commissioner from "."
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "spree_products" does not exist
LINE 8:  WHERE a.attrelid = '"spree_products"'::regclass
                            ^
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `block (2 levels) in query'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:820:in `column_definitions'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `columns'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/schema_cache.rb:112:in `block in columns'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/schema_cache.rb:111:in `fetch'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/schema_cache.rb:111:in `columns'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/schema_cache.rb:120:in `block in columns_hash'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/schema_cache.rb:119:in `fetch'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/schema_cache.rb:119:in `columns_hash'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:553:in `load_schema!'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/attributes.rb:250:in `load_schema!'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:539:in `block in load_schema'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:536:in `synchronize'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:536:in `load_schema'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:397:in `columns'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activerecord-6.1.7/lib/active_record/model_schema.rb:466:in `column_names'
/Users/theachoem/Coding/Webs/central_market/commissioner/app/models/concerns/spree_cm_commissioner/product_type.rb:11:in `block in <module:ProductType>'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/concern.rb:136:in `class_eval'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/concern.rb:136:in `append_features'
/Users/theachoem/Coding/Webs/central_market/commissioner/app/models/spree/product_decorator.rb:4:in `include'
/Users/theachoem/Coding/Webs/central_market/commissioner/app/models/spree/product_decorator.rb:4:in `prepended'
/Users/theachoem/Coding/Webs/central_market/commissioner/app/models/spree/product_decorator.rb:50:in `prepend'
/Users/theachoem/Coding/Webs/central_market/commissioner/app/models/spree/product_decorator.rb:50:in `<top (required)>'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/Users/theachoem/Coding/Webs/central_market/commissioner/lib/spree_cm_commissioner/engine.rb:18:in `block in activate'
<internal:dir>:220:in `glob'
/Users/theachoem/Coding/Webs/central_market/commissioner/lib/spree_cm_commissioner/engine.rb:17:in `activate'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `catch'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
/Users/theachoem/Coding/Webs/central_market/commissioner/spec/dummy/config/environment.rb:5:in `<top (required)>'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/railties-6.1.7/lib/rails/application.rb:367:in `require_environment!'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/railties-6.1.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/Users/theachoem/Coding/Webs/central_market/commissioner/vendor/cache/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/theachoem/.rbenv/versions/3.1.3/bin/bundle:25:in `load'
/Users/theachoem/.rbenv/versions/3.1.3/bin/bundle:25:in `<main>'
```

**Comment by theachoem** [comment]
This error caused by calling column_name on setting up before creating db.
